import { InstitutionData, SessionUser } from "@/types";

export const DEFAULT_INSTITUTIONS: InstitutionData[] = [
  {
    id: "inst-police",
    name: "Ophelia Police Department",
    slug: "police",
    description: "Ophelia Police Department (OPD) - To Protect and to Serve",
    logo: "/logos/police.jpg",
    primaryColor: "#0066FF",
    currencySymbol: "Rp",
    defaultHourlyRate: 50000,
    status: "ACTIVE",
    discordRoleNames: [
      "CHIEF OF POLICE",
      "OFFICER",
      "SWAT",
      "HIGHWAY PATROL",
      "Police",
      "Police Officer",
      "Cadet",
      "Polisi",
      "Chief",
    ],
  },
  {
    id: "inst-medical",
    name: "Ophelia Medical Center",
    slug: "medical",
    description: "Ophelia Medical Center (OMC) - Care • Professionalism • Dedication",
    logo: "/logos/medical.jpg",
    primaryColor: "#00B4D8",
    currencySymbol: "Rp",
    defaultHourlyRate: 50000,
    status: "ACTIVE",
    discordRoleNames: [
      "MEDIS",
      "PETINGGI MEDIS",
      "EMS",
      "EMS Director",
      "Supervisor",
      "Paramedic",
      "Doctor",
      "Dokter",
      "Perawat",
      "Surgeon",
      "Hospital",
      "Rumah Sakit",
    ],
  },
  {
    id: "inst-mechanic",
    name: "Ophelia Custom Garage",
    slug: "mechanic",
    description: "Ophelia Custom Garage (OCG) - Automotive Tuning, Performance & Vehicle Maintenance",
    logo: "/logos/mechanic.png",
    primaryColor: "#FF9900",
    currencySymbol: "Rp",
    defaultHourlyRate: 55000,
    status: "ACTIVE",
    discordRoleNames: [
      "BENGKEL",
      "PETINGGI BENGKEL",
      "Mechanic",
      "Bengkel",
      "Mekanik",
      "Petinggi Mekanik",
      "Mechanic Owner",
      "Senior Mechanic",
      "Leadhand Mechanic",
      "Apprentice",
      "Custom Garage",
      "OCG",
      "Tuner",
    ],
  },
  {
    id: "inst-restaurant",
    name: "Ophelia Restaurant & Lounge",
    slug: "restaurant",
    description: "Ophelia Fine Dining & Lounge - Luxury Culinary & Hospitality Experience",
    logo: "/logos/restaurant.png",
    primaryColor: "#D4AF37",
    currencySymbol: "Rp",
    defaultHourlyRate: 45000,
    status: "ACTIVE",
    discordRoleNames: [
      "SERVERS RESTO",
      "PETINGGI RESTO",
      "Restaurant",
      "Resto",
      "Server Resto",
      "Petinggi Resto",
      "Restaurant Manager",
      "Supervisor",
      "Employee",
      "Chef",
      "Cook",
      "Bartender",
      "Barista",
      "Waiter",
    ],
  },
  {
    id: "inst-pemerintah",
    name: "Pemerintah Kota Ophelia",
    slug: "pemerintah",
    description: "Pemerintahan Kota Ophelia - Layanan Publik, Regulasi & Administrasi Kota",
    logo: "/logos/ophelia-logo.png",
    primaryColor: "#059669",
    currencySymbol: "Rp",
    defaultHourlyRate: 60000,
    status: "ACTIVE",
    discordRoleNames: [
      "PEMERINTAH",
      "PETINGGI PEMERINTAH",
      "Pemerintah",
      "Petinggi Pemerintah",
      "Staff Pemerintah",
    ],
  },
];

export const KNOWN_DISCORD_ROLE_IDS: Record<string, string> = {
  "1482622396954312809": "ADMIN",
  "1482622396954312808": "PIMPINAN",
  "1482622396954312807": "CHIEF OF POLICE",
  "1508742513874440303": "SWAT",
  "1508742898194186330": "HIGHWAY PATROL",
  "1522915139072950312": "OFFICER",
  "1482622396946055227": "MEDIS",
  "1482622396954312805": "PETINGGI MEDIS",
  "1482622396946055223": "BENGKEL",
  "1482622396946055224": "PETINGGI BENGKEL",
  "1482622396946055225": "SERVERS RESTO",
  "1482622396946055226": "PETINGGI RESTO",
  "1482622396946055221": "PEMERINTAH",
  "1482622396946055222": "PETINGGI PEMERINTAH",
  "1482622396946055219": "PDM",
  "1482622396946055220": "TAXI",
};

export const DEFAULT_POSITION_SALARIES: Record<
  string,
  Record<string, { hourlyRate: number; minDutyHours: number }>
> = {
  police: {
    "Cadet": { hourlyRate: 35000, minDutyHours: 10 },
    "Officer": { hourlyRate: 50000, minDutyHours: 15 },
    "Highway Patrol": { hourlyRate: 65000, minDutyHours: 15 },
    "SWAT": { hourlyRate: 75000, minDutyHours: 20 },
    "Senior Officer": { hourlyRate: 65000, minDutyHours: 20 },
    "Sergeant": { hourlyRate: 80000, minDutyHours: 25 },
    "Commander": { hourlyRate: 110000, minDutyHours: 30 },
    "Chief of Police": { hourlyRate: 150000, minDutyHours: 30 },
  },
  medical: {
    "Medis": { hourlyRate: 45000, minDutyHours: 10 },
    "Paramedic": { hourlyRate: 45000, minDutyHours: 10 },
    "Doctor": { hourlyRate: 70000, minDutyHours: 15 },
    "Surgeon": { hourlyRate: 95000, minDutyHours: 20 },
    "Petinggi Medis": { hourlyRate: 140000, minDutyHours: 25 },
    "Director of Emergency Medicine": { hourlyRate: 140000, minDutyHours: 25 },
  },
  mechanic: {
    "Apprentice": { hourlyRate: 35000, minDutyHours: 10 },
    "Mekanik": { hourlyRate: 55000, minDutyHours: 15 },
    "Mechanic": { hourlyRate: 55000, minDutyHours: 15 },
    "Senior Mechanic": { hourlyRate: 75000, minDutyHours: 20 },
    "Leadhand Mechanic": { hourlyRate: 100000, minDutyHours: 25 },
    "Petinggi Bengkel": { hourlyRate: 110000, minDutyHours: 25 },
  },
  restaurant: {
    "Employee": { hourlyRate: 40000, minDutyHours: 10 },
    "Server Resto": { hourlyRate: 45000, minDutyHours: 10 },
    "Servers Resto": { hourlyRate: 45000, minDutyHours: 10 },
    "Chef": { hourlyRate: 70000, minDutyHours: 15 },
    "Cook": { hourlyRate: 50000, minDutyHours: 10 },
    "Bartender": { hourlyRate: 50000, minDutyHours: 10 },
    "Barista": { hourlyRate: 45000, minDutyHours: 10 },
    "Waiter": { hourlyRate: 40000, minDutyHours: 10 },
    "Supervisor": { hourlyRate: 60000, minDutyHours: 15 },
    "Petinggi Resto": { hourlyRate: 90000, minDutyHours: 20 },
    "Restaurant Manager": { hourlyRate: 90000, minDutyHours: 20 },
  },
  pemerintah: {
    "Staff Pemerintah": { hourlyRate: 60000, minDutyHours: 15 },
    "Petinggi Pemerintah": { hourlyRate: 150000, minDutyHours: 25 },
  },
};

export const DEMO_PERSONAS: (SessionUser & {
  roleTitle: string;
  institutionSlugs: string[];
  roleLevels: Record<string, "MEMBER" | "LEADER" | "SUPER_ADMIN">;
})[] = [
  {
    id: "user-john",
    discordId: "982736410293847101",
    discordUsername: "johndoe_lspd",
    displayName: "Officer John Doe",
    discordAvatar: "https://cdn.discordapp.com/embed/avatars/0.png",
    discordRoles: ["Police", "Police Officer", "Citizen"],
    isSuperAdmin: false,
    roleTitle: "Officer @ LSPD",
    institutionSlugs: ["police"],
    roleLevels: {
      police: "MEMBER",
    },
  },
  {
    id: "user-gordon",
    discordId: "982736410293847102",
    discordUsername: "chief_gordon",
    displayName: "Chief James Gordon",
    discordAvatar: "https://cdn.discordapp.com/embed/avatars/1.png",
    discordRoles: ["Police", "Police Chief", "Mechanic", "Citizen"],
    isSuperAdmin: false,
    roleTitle: "Police Chief & Mechanic Lead",
    institutionSlugs: ["police", "mechanic"],
    roleLevels: {
      police: "LEADER",
      mechanic: "MEMBER",
    },
  },
  {
    id: "user-sarah",
    discordId: "982736410293847103",
    discordUsername: "dr_sarah",
    displayName: "Dr. Sarah Connor",
    discordAvatar: "https://cdn.discordapp.com/embed/avatars/2.png",
    discordRoles: ["EMS", "EMS Director", "Citizen"],
    isSuperAdmin: false,
    roleTitle: "EMS Director @ Ophelia Medical Center",
    institutionSlugs: ["medical"],
    roleLevels: {
      medical: "LEADER",
    },
  },
  {
    id: "user-alex",
    discordId: "982736410293847104",
    discordUsername: "alex_customs",
    displayName: "Alex Rivera",
    discordAvatar: "https://cdn.discordapp.com/embed/avatars/3.png",
    discordRoles: ["Mechanic", "Senior Mechanic", "Citizen"],
    isSuperAdmin: false,
    roleTitle: "Senior Mechanic @ Ophelia Custom Garage",
    institutionSlugs: ["mechanic"],
    roleLevels: {
      mechanic: "MEMBER",
    },
  },
  {
    id: "user-marcus",
    discordId: "982736410293847199",
    discordUsername: "marcus_owner",
    displayName: "Marcus Vance",
    discordAvatar: "https://cdn.discordapp.com/embed/avatars/4.png",
    discordRoles: ["Admin", "Server Owner", "Police", "EMS", "Mechanic", "Restaurant"],
    isSuperAdmin: true,
    roleTitle: "Super Admin / Server Owner",
    institutionSlugs: ["police", "medical", "mechanic", "restaurant"],
    roleLevels: {
      police: "SUPER_ADMIN",
      medical: "SUPER_ADMIN",
      mechanic: "SUPER_ADMIN",
      restaurant: "SUPER_ADMIN",
    },
  },
];
